{% set name = "mne-bids" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8af1d74172a639519f7f48fc5663f007201b1d8762c44afa09be9c090859cc2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - scipy
    - nibabel
    - mne

test:
  imports:
    - mne_bids

about:
  home: https://mne.tools/mne-bids/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An MNE project for organizing and formatting MEG and EEG data according to the BIDS specification
  dev_url: https://github.com/mne-tools/mne-bids

extra:
  recipe-maintainers:
    - hoechenberger
    - jasmainak
