travis:
  secure:
    BINSTAR_TOKEN: V+5tmH4RPwOCEtHER54BIiONGVIVa4HIVlcrb01KLg9BAQXNVQO6q6WV5LzqIeowFcm7r/XZOT823CX74TbRWoYNT9jiAz49AJxKXlpiiP9qpN6O0+rMl9/EEVFXtA6WxTkkrk6yhUV8LW9MIxKSh4Uv3zyn+AN2rl7MZyIYMNh/Ok5K5W8nb3mnfRZ0daMqUuC2ylRJY95TIrE2s83tEJh769gzDYM6mhF37SKPtDttkk2/OuXsXOgeTNDvhJ7iWKVQI8C6lJTqwoB2J4USzK2aEodJxfNtrCIB2u6tcRUuOOjfyElzf7G/d5yHkHsYAoWLjQyheZkS6UymA1SVD0AwL4KxLLgdA3iHxEWa9ha1ZyEZzmmqEgIvnKkFWDNRPbitbrRjkaaWdFKXdl/gJVwVp4Wn4ZGg7M4S0lbaFgwZtLGXTOhLDelyNyPipI6fdWsMP2Sv2+XtKsA0CbvGgJ7kGK+ixU1BaVK/yjlxcBgwp/YgZSFFrvZ2BDq0rtqdo5DjVhBp79RgqSisAG2S9cio4wLZhOPwxz7LDoUJG1BJlApUOYHTJAxmQYIvVT47g8I/7ArpJLa5NX87iwzlZSVMjA/rH8dOjRzwCIPIT498kiXOwnGVVP1kWT8nRmcQGb1YqTNyR2Qq87RGcATQnqv2KGDGtMhDEXPDotv/i9I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
