travis:
  secure:
    BINSTAR_TOKEN: Y9zrEDhHiioTOakyW0lO1Xmbm47oPyu/T1tH0vw41AstnbSL1R6nmvRgyVmUbolMJEoZ9DmxSlnageiwOCQEeQz0xAzIRSziD5iflFVl6e9A5FyLl3lXQ6tUAi/adGjsiH0rKBNwwjYzUclOujqy8D2go5Gf1VxvEcmWPqy1DgzoH1hGEpgrFCblDwKKjY2y7vWWj8O520924Exndo9Qd0GkB92iRsPM89pNBGw1AQx6ain6zcH5UZfFWEyTs7qcgmHGEsr65Mynhb9m45Bm1bP2ET1KFG//ghhc4PIRECVIF52htltcIaqF2VjU4WRuOlMYuqrSIRR+k9wcOYkCw1obHRiMT9PeVDZNGKc53CQ3Ck2bRCtbLZ/FrZL0p6mhr15F9rI6AmCyoBxu71Ihd1hJ7h6q3YPusmFbQozgAfefYrmd3KxkVqFr1vveCu90RAjd3Va0x8f51QdkEdV8oXDdQnIA5ud8ePgRlIhbKBGsgP6TglB6btYdcTzTJQvtYwNBVG+h/1+y0MyMR3/B7c1CFiOKAxRuuaXdmZCmafLOOTTBeI64Ri+GwVb/it+CKjj4rIMeg+ktCCvaw9W2t0G5vpxaVMV+4OA+QVkDw69miH1JDnW4uex4US9pVSjD0359A917EEEswVgrIVCMuu0Bt7n3594gnI1+krw6tGc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
